In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

### Loading the Datasets

In [2]:
#Loading Book dataset
book_df=pd.read_csv(r"C:\Users\HP\Desktop\Bookify\Database\Datasets\Books.csv")

#Loading user dataset
user_df=pd.read_csv(r"C:\Users\HP\Desktop\Bookify\Database\Datasets\Users.csv")

#Loading Rating dataset
rating_df=pd.read_csv(r"C:\Users\HP\Desktop\Bookify\Database\Datasets\Ratings.csv")

## BOOKS DATASET

In [3]:
book_df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
book_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271359 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [5]:
book_df.describe()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
count,271360,271360,271359,271360,271358,271360,271360,271357
unique,271360,242135,102023,202,16807,271044,271044,271041
top,0195153448,Selected Poems,Agatha Christie,2002,Harlequin,http://images.amazon.com/images/P/185326119X.0...,http://images.amazon.com/images/P/185326119X.0...,http://images.amazon.com/images/P/225307649X.0...
freq,1,27,632,13903,7535,2,2,2

In [6]:
book_df.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [7]:
book_df.shape

(271360, 8)

### 1. Remove Duplicates

In [8]:
#identifying the duplicates
book_df.duplicated().sum()

0

### 2. Handle Missing Values

In [9]:
#Finding the Missing values
book_df.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
# Filling missing Book author values with 'Unknown'
book_df['Book-Author'].fillna('Unknown', inplace=True)

# Filling missing Publisher values with 'Unknown'
book_df['Publisher'].fillna('Unknown', inplace=True)

# Filling missing large image URLs values with 'Unknown'
book_df['Image-URL-L'].fillna('Unknown', inplace=True)

In [11]:
book_df.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            0
dtype: int64

### 3. Standardize Book Publication Years

In [12]:
# Convert year column to numeric, handle invalid entries
book_df['Year-Of-Publication'] = pd.to_numeric(book_df['Year-Of-Publication'], errors='coerce')

# Replace years outside 1800–2025 range with NaN
book_df.loc[(book_df['Year-Of-Publication'] < 1800) | (book_df['Year-Of-Publication'] > 2025), 'Year-Of-Publication'] = None

# Fill missing years with median of valid years
year = int(book_df['Year-Of-Publication'].median())
book_df['Year-Of-Publication'].fillna(year, inplace=True)

# Convert to integer
book_df['Year-Of-Publication'] = book_df['Year-Of-Publication'].astype(int)

In [13]:
#Saving the Cleaned Book Dataset
book_df.to_csv(r'C:\Users\HP\Desktop\Bookify\Database\Cleaned_Datasets\Books_Cleaned.csv', index=False)

## USER DATASET

In [14]:
user_df.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [15]:
user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [16]:
user_df.describe()

            User-ID            Age
count  278858.00000  168096.000000
mean   139429.50000      34.751434
std     80499.51502      14.428097
min         1.00000       0.000000
25%     69715.25000      24.000000
50%    139429.50000      32.000000
75%    209143.75000      44.000000
max    278858.00000     244.000000

In [17]:
user_df.shape

(278858, 3)

### 1. Remove Duplicates

In [18]:
#identifying the duplicates
user_df.duplicated().sum()

0

### 2. Handle Missing Values

In [19]:
#Finding the Missing values
user_df.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [20]:
# Filter rows with 'Age' missing or between 5 and 100.
user_df = user_df[(user_df['Age'].isnull()) | ((user_df['Age'] >= 5) & (user_df['Age'] <= 100))]

# Fill missing 'Age' values with the median.
user_df['Age'].fillna(user_df['Age'].median(), inplace=True)

In [21]:
#Finding the Missing values
user_df.isnull().sum()

User-ID     0
Location    0
Age         0
dtype: int64

In [22]:
#Saving the Cleaned Users Dataset
user_df.to_csv(r'Cleaned_Datasets\Users_Cleaned.csv', index=False)

## RATING DATASET

In [23]:
rating_df.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [24]:
rating_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [25]:
rating_df.describe()

            User-ID   Book-Rating
count  1.149780e+06  1.149780e+06
mean   1.403864e+05  2.866950e+00
std    8.056228e+04  3.854184e+00
min    2.000000e+00  0.000000e+00
25%    7.034500e+04  0.000000e+00
50%    1.410100e+05  0.000000e+00
75%    2.110280e+05  7.000000e+00
max    2.788540e+05  1.000000e+01

In [26]:
rating_df.shape

(1149780, 3)

### 1. Remove Duplicates

In [27]:
#identifying the duplicates
rating_df.duplicated().sum()

0

### 2. Handle Missing Values

In [28]:
#Finding the Missing values
rating_df.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [29]:
#Saving the Cleaned Rating Dataset
rating_df.to_csv(r'C:\Users\HP\Desktop\Bookify\Database\Cleaned_Datasets\Ratings_Cleaned.csv', index=False)